// mux-521-angular-complete/src/app/components/examples/o-pad-8-way/o-pad-8-way.component.ts
import { Component,Input} from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-o-pad-8-way-example',
  templateUrl: './o-pad-8-way.component.html',
  styleUrl: './o-pad-8-way.component.scss'
})
export class OPad8WayExampleComponent {
    // Use the @Input decorator to define the join property.
    @Input() join: string = 'MediaControl.Dpad';

    /** Pulses the up digital join */
    up(): void {
      CrComLib.pulseDigital(this.join + '.Up');
    }
    /** Pulses the down digital join */
    down(): void {
      CrComLib.pulseDigital(this.join + '.Down');
    }
    /** Pulses the up digital join */
    left(): void {
      CrComLib.pulseDigital(this.join + '.Left');
    }
    /** Pulses the up digital join */
    right(): void {
      CrComLib.pulseDigital(this.join + '.Right');
    }
    /** Pulses the up center join */
    center(): void {
      CrComLib.pulseDigital(this.join + '.Center');
    }
  }

<nav class="o-pad">
  <button class="o-pad__button o-pad__button--up" (click)="up()">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--up-right">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--right" (click)="right()">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--down-right">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--up-left">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--left" (click)="left()">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--down-left">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--down" (click)="down()">
    <img src="assets/images/icons/navigation/arrow.svg" />
  </button>

  <button class="o-pad__button o-pad__button--centre" (click)="center()">OK</button>
</nav>

// mux-521-react-complete/src/components/OPad8Way/OPad8Way.tsx
import React, { useContext } from 'react';

// Import the styles from the scss file
import styles from './OPad8Way.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const DNavComponent = ({ join = 'MediaControl.Dpad' }) => {

  // Access the pulseDigital function
  const { pulseDigital } = useContext(CrComLibContext);

  const up = () => {
    pulseDigital(`${join}.Up`);
  };

  const down = () => {
    pulseDigital(`${join}.Down`);
  };

  const left = () => {
    pulseDigital(`${join}.Left`);
  };

  const right = () => {
    pulseDigital(`${join}.Right`);
  };

  const ok = () => {
    pulseDigital(`${join}.Center`);
  };

  // Render the component UI
  return (
    <nav className={styles["o-pad"]}>
      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--up']}`} onClick={up}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>
      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--up-right']}`}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--right']}`} onClick={right}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--down-right']}`}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--up-left']}`}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--left']}`} onClick={left}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--down-left']}`}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--down']}`} onClick={down}>
        <img src="./images/icons/navigation/arrow.svg" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--centre']}`} onClick={ok}>
      </button>
    </nav>
  );
};

export default DNavComponent;
