// mux-521-angular-complete/src/app/popups/airmedia/airmedia.component.ts
import { Component, NgZone, OnDestroy, OnInit,signal } from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-airmedia',
  templateUrl: './airmedia.component.html',
  styleUrl: './airmedia.component.scss',
})
export class AirmediaComponent implements OnInit, OnDestroy {
 // The IP address / hostname of the airmedia device
  address =signal('0.0.0.0');
  // Subscription to the address serial join
  addressSubscription!: string;
  // The current pin of the airmedia device
  pin =signal('1988');
  // Subscription to the pin serial join
  pinSubscription!: string;

  constructor(private ngZone: NgZone) {}

  // ngOnInit lifecycle hook
  ngOnInit(): void {
    // Subscribe to the address serial join
    this.addressSubscription = CrComLib.subscribeState(
      's',
      'AirMediaInfo.AirmediaAddressFb.Indirect',
      (address: string) => {
        if (address.length == 0) return;
        console.log('Title Bar - Title Received: ' + address);
        this.ngZone.run(() => this.address.set(address));
      }
    );

    // Subscribe to the pin serial join
    this.pinSubscription = CrComLib.subscribeState(
      's',
      'AirMediaInfo.AirmediaPinFb.Indirect',
      (pin: string) => {
        if (pin.length == 0) return;
        console.log('airmedia pin received: ' + pin);
        this.ngZone.run(() => this.pin.set(pin));
      }
    );
  }

  // ngOnDestroy lifecycle hook
  ngOnDestroy(): void {
    // Unsubscribe from the address state
    CrComLib.unsubscribeState(
      's',
      'AirMediaInfo.AirmediaAddressFb.Indirect',
      this.addressSubscription
    );

    // Unsubscribe from the pin state
    CrComLib.unsubscribeState(
      's',
      'AirMediaInfo.AirmediaPinFb.Indirect',
      this.pinSubscription
    );
  }
}

<div class="airmedia">
  <span>AirMedia Address:</span>
  <span class="text-highlight">{{ address() }}</span>

  <span>Access Pin:</span>
  <span class="text-highlight">{{ pin() }}</span>
</div>

// mux-521-react-complete/src/components/AirMedia/AirMedia.tsx
import React, { useState, useEffect, useContext } from 'react';

// Import the styles from the scss file
import styles from './AirMedia.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const AirmediaComponent: React.FC = () => {

  // Access the subscribeState and unsubscribeState functions
  const { subscribeState, unsubscribeState } = useContext(CrComLibContext);

  // Initialize the address and pin states
  const [address, setAddress] = useState('0.0.0.0');
  const [pin, setPin] = useState('1988');

  useEffect(() => {

    // Subscribe to the AirMedia address
    const addressSubscription = subscribeState(
      's',
      'AirMediaInfo.AirmediaAddressFb.Indirect',
      (newAddress: string) => {
        if (newAddress.length === 0) return;
        console.log('Airmedia - Adddress Received: ' + newAddress);
        setAddress(newAddress);
      }
    );

    // Subscribe to the AirMedia pin
    const pinSubscription = subscribeState(
      's',
      'AirMediaInfo.AirmediaPinFb.Indirect',
      (newPin: string) => {
        if (newPin.length > 0) return;
        console.log('Airmedia pin received: ' + newPin);
        setPin(newPin);
      }
    );

    // Cleanup function for component unmount
    return () => {
      unsubscribeState('s', 'AirMediaInfo.AirmediaAddressFb.Indirect', addressSubscription);
      unsubscribeState('s', 'AirMediaInfo.AirmediaPinFb.Indirect', pinSubscription);
    };
  }, [subscribeState, unsubscribeState]); // The useEffect hook will only run when the subscribeState or unsubscribeState functions change

  // Render the component UI
  return (
    <>
      <div className={styles["airmedia"]}>
        <span>AirMedia Address:</span>
        <span className="text-highlight">{address}</span>
        <span>Access Pin:</span>
        <span className="text-highlight">{pin}</span>
      </div>
    </>
  );
};

export default AirmediaComponent;
