// mux-521-angular-complete/src/app/components/volume/volume.component.ts
import {
  Component,
  OnDestroy,
  OnInit,
  NgZone,
  signal,
  computed,
} from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-volume',
  templateUrl: './volume.component.html',
  styleUrl: './volume.component.scss',
})
export class VolumeComponent implements OnInit, OnDestroy {
  // Boolean to hold mute state
  mute = signal(false);
  // Subscription string for mute state
  muteSubscription!: string;

  // Signal to hold volume level
  level = signal(0);
  // Scale the level from 0-65535 to 0-100 for the gauge height.
  gaugeHeight = computed(() => this.level() / 655.35 + '%');

  // Subscription string for volume level
  levelSubscription!: string;

  constructor(private ngZone: NgZone) {}

  ngOnInit(): void {
    // Subscribe to mute state
    this.muteSubscription = CrComLib.subscribeState(
      'b',
      'MainPage.MutedFeedback.Visibility',
      (mute: boolean) => {
        this.ngZone.run(() => this.mute.set(mute));
        console.log('The mute state is: ' + mute);
      }
    );
    // Subscribe to volume level
    this.levelSubscription = CrComLib.subscribeState(
      'n',
      'MainPage.VolumeBar.Touchfb',
      (level: number) => {
        this.ngZone.run(() => this.level.set(level));
        console.log('The volume level is: ' + level);
      }
    );
  }

  ngOnDestroy(): void {
    // Unsubscribe from mute state
    CrComLib.unsubscribeState(
      'b',
      'MainPage.MutedFeedback.Visibility',
      this.muteSubscription
    );

    // Unsubscribe from volume level
    CrComLib.unsubscribeState(
      'n',
      'MainPage.VolumeBar.Touchfb',
      this.levelSubscription
    );
  }

  RampUp(state: boolean): void {
    CrComLib.setDigital('MainPage.VolumeButtonList.Button1ItemPress', state);
  }

  RampDown(state: boolean): void {
    CrComLib.setDigital('MainPage.VolumeButtonList.Button3ItemPress', state);
  }
  // Function to toggle mute
  MuteToggle(): void {
    CrComLib.pulseDigital('MainPage.VolumeButtonList.Button2ItemPress');
  }
}

<div class="volume">
  <div class="volume__buttons">
    <button
      class="volume__button"
      (pointerdown)="RampUp(true)"
      (pointerup)="RampUp(false)"
      (pointerout)="RampUp(false)"
    >
      <img src="assets/images/icons/volume/speaker-up.svg" />
    </button>

    <button
      class="volume__button"
      [class.selected]="mute()"
      (click)="MuteToggle()"
    >
      <img src="assets/images/icons/volume/speaker-mute.svg" />
    </button>
    <button
      class="volume__button"
      (pointerdown)="RampDown(true)"
      (pointerup)="RampDown(false)"
      (pointerout)="RampDown(false)"
    >
      <img src="assets/images/icons/volume/speaker-down.svg" />
    </button>
  </div>

  <div class="volume__gauge" style="mix-blend-mode: screen">
    <div class="volume__gauge--indicator" [style.height]="gaugeHeight()"></div>
    <ul class="volume__gauge--segments">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
</div>

// mux-521-react-complete/src/components/Volume/Volume.tsx
import React, { useEffect, useState, useContext } from 'react';

// Import the styles from the scss file
import styles from './Volume.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const VolumeComponent: React.FC = () => {

  // Access the subscribeState, unsubscribeState, and pulseDigital functions
  const { subscribeState, unsubscribeState, publishEvent, pulseDigital } = useContext(CrComLibContext);

  /* --------------------------------------------------------------------------------- */
  /* TODO - Exercise 4.1: Add a state for our mute state and initialise it with false */
  /* --------------------------------------------------------------------------------- */
  const [mute, setMute] = useState<boolean>(false);


  /* ------------------------------------------------------------------------------ */
  /* TODO - Exercise 4.2: Add a state for our level value and initialise it with 0 */
  /* ------------------------------------------------------------------------------ */
  const [level, setLevel] = useState<number>(0);

  // Compute gauge height based on level
  const gaugeHeight = `0%`;


  /* ------------------------------------------------------------------------------ */
  /* TODO - Exercise 4.7: Create a function to correctly scale our gauge            */
  /* ------------------------------------------------------------------------------ */

  useEffect(() => {
    /* ------------------------------------------------------------------------------------------------------------- */
    /* TODO - Exercise 4.3: Subscribe to our mute & level joins                                                      */
    /* HINT: - The join for the mute state is: 'MainPage.MutedFeedback.Visibility'                                   */
    /* HINT: - The join for the volume level is: 'MainPage.VolumeBar.Touchfb'                                        */
    /* HINT: - The standard method to subscribe to a join is: 'handle = CrComLib.subscribeState(type, join, action)' */
    /* ------------------------------------------------------------------------------------------------------------- */
    // Subscribe to mute state
    const muteSubscription = subscribeState(
      'b',
      'MainPage.MutedFeedback.Visibility',
      (mute: boolean) => {
        setMute(mute);
        console.log('The mute state is: ' + mute);
      }
    );
    // Subscribe to volume level
    const levelSubscription = subscribeState(
      'n',
      'MainPage.VolumeBar.Touchfb',
      (level: number) => {
        setLevel(level);
        console.log('The volume level is: ' + level);
      }
    );



    // Cleanup function for component unmount
    return () => {
      /* ------------------------------------------------------------------------------------------------------------- */
      /* TODO - Exercise 4.4: Unsubscribe to our mute & level joins                                                    */
      /* ------------------------------------------------------------------------------------------------------------- */
      unsubscribeState('b', 'MainPage.MutedFeedback.Visibility', muteSubscription);
      unsubscribeState('n', 'MainPage.VolumeBar.Touchfb', levelSubscription);
    };
  }, [subscribeState, unsubscribeState]);

  const rampUp = (state: boolean) => {
    publishEvent('b', 'MainPage.VolumeButtonList.Button1ItemPress', state);
  };

  const rampDown = (state: boolean) => {
    publishEvent('b', 'MainPage.VolumeButtonList.Button3ItemPress', state);
  };

  const muteToggle = () => {
    pulseDigital('MainPage.VolumeButtonList.Button2ItemPress');
  };

  // Render the component UI
  return (
    <div className={styles["volume"]}>
      <div className={styles["volume__buttons"]}>
        <button
          className={styles["volume__button"]}
          onPointerDown={() => rampUp(true)}
          onPointerUp={() => rampUp(false)}
          onPointerOut={() => rampUp(false)}
        >
          <img src='./images/icons/volume/speaker-up.svg' alt="" />
        </button>

        {/* ---------------------------------------------------------------------------------------- */}
        {/* TODO - Exercise 4.5: Apply volume__button--selected to the mute button Hint mute()       */}
        {/* paste the code after className={styles["volume__button"]                                 */}
        {/* ---------------------------------------------------------------------------------------- */}
        <button
          className={`${styles["volume__button"]} ${mute ? styles["selected"] : ''}`}
          onClick={muteToggle}
        >
          <img src='./images/icons/volume/speaker-mute.svg' alt="" />
        </button>

        <button
          className={styles["volume__button"]}
          onPointerDown={() => rampDown(true)}
          onPointerUp={() => rampDown(false)}
          onPointerOut={() => rampDown(false)}
        >
          <img src='./images/icons/volume/speaker-down.svg' alt="" />
        </button>
      </div>

      <div className={styles["volume__gauge"]} style={{ mixBlendMode: 'screen' }}>
        {/* -------------------------------------------------------------------------- */}
        {/* TODO - Exercise 4.6: Apply style.height to the indicator                   */}
        {/* paste the code after className={styles["volume__gauge--indicator"]}        */}
        {/* -------------------------------------------------------------------------- */}
        <div className={styles["volume__gauge--indicator"]} style={{ height: `${level/ 655.35}%` }}></div>
        {/* <ul className={styles["volume__gauge--segments"]}>
          {[...Array(10)].map((_, i) => (
            <li key={i}></li>
          ))}
        </ul> */}
      </div>
    </div>
  );
};

export default VolumeComponent;
