// mux-521-angular-complete/src/app/components/examples/o-pad/o-pad.component.ts
import { Component,Input } from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone:true,
  selector: 'app-o-pad-example',
  templateUrl: './o-pad.component.html',
  styleUrl: './o-pad.component.scss'
})
export class OPadExampleComponent {
   // Use the @Input decorator to define the join property.
   @Input() join: string = 'MediaControl.Dpad';

   /** Pulses the up digital join */
   up(): void {
     CrComLib.pulseDigital(this.join + '.Up');
   }
   /** Pulses the down digital join */
   down(): void {
     CrComLib.pulseDigital(this.join + '.Down');
   }
   /** Pulses the up digital join */
   left(): void {
     CrComLib.pulseDigital(this.join + '.Left');
   }
   /** Pulses the up digital join */
   right(): void {
     CrComLib.pulseDigital(this.join + '.Right');
   }
   /** Pulses the up center join */
   center(): void {
     CrComLib.pulseDigital(this.join + '.Center');
   }
 }

<nav class="o-pad">
  <button class="o-pad__button o-pad__button--up" (click)="up()">
    <img src="assets/images/icons/navigation/up.svg" />
  </button>

  <button class="o-pad__button o-pad__button--right" (click)="right()">
    <img src="assets/images/icons/navigation/right.svg" />
  </button>

  <button class="o-pad__button o-pad__button--left" (click)="left()">
    <img src="assets/images/icons/navigation/left.svg" />
  </button>

  <button class=" o-pad__button o-pad__button--down" (click)="down()">
    <img src="assets/images/icons/navigation/down.svg" />
  </button>

  <button class="o-pad__button o-pad__button--centre" (click)="center()">OK</button>
</nav>

// mux-521-react-complete/src/components/OPad/OPad.tsx
import React, { useContext } from 'react';

// Import the styles from the scss file
import styles from './OPad.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const DNavComponent = ({ join = 'MediaControl.Dpad' }) => {

  // Access the pulseDigital function
  const { pulseDigital } = useContext(CrComLibContext);

  const up = () => {
    pulseDigital(`${join}.Up`);
  };

  const down = () => {
    pulseDigital(`${join}.Down`);
  };

  const left = () => {
    pulseDigital(`${join}.Left`);
  };

  const right = () => {
    pulseDigital(`${join}.Right`);
  };

  const ok = () => {
    pulseDigital(`${join}.Center`);
  };

  // Render the component UI
  return (
    <nav className={styles["o-pad"]}>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--up']}`} onClick={up}>
        <img src="./images/icons/navigation/up.svg" alt="Up" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--right']}`} onClick={right}>
        <img src="./images/icons/navigation/right.svg" alt="Right" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--left']}`} onClick={left}>
        <img src="./images/icons/navigation/left.svg" alt="Left" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--down']}`} onClick={down}>
        <img src="./images/icons/navigation/down.svg" alt="Down" />
      </button>

      <button className={`${styles['o-pad__button']} ${styles['o-pad__button--centre']}`} onClick={ok}>
      </button>
    </nav>
  );
};

export default DNavComponent;
