// mux-521-angular-complete/src/app/components/source-list/source-list.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  NgZone,
  Input,
  signal,
  WritableSignal,
} from '@angular/core';

import { SourceButton } from '../../../models/sourcebutton';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-source-list',
  templateUrl: './source-list.component.html',
  styleUrl: './source-list.component.scss',
})
export class SourceListComponent implements OnInit, OnDestroy {
  @Input() sources = 0;

  titleSubscription: string[] = new Array(this.sources);
  selectedSubscription: string[] = new Array(this.sources);

  SourceButton!: WritableSignal<SourceButton[]>;

  constructor(private ngZone: NgZone) {}

  ngOnInit(): void {
    this.SourceButton = signal(
      new Array(this.sources).fill(new SourceButton())
    );

    for (let i = 0; i < this.sources; i++) {
      this.titleSubscription[i] = CrComLib.subscribeState(
        's',
        `MainPage.SourceList.Button${i + 1}Text`,
        (title: string) => {
          console.log('Received a title for button: ' + title);
          this.updateSourceButton(i, 'title', title);
        }
      );

      this.selectedSubscription[i] = CrComLib.subscribeState(
        'b',
        `MainPage.SourceList.Button${i + 1}ItemSelected`,
        (state: boolean) => {
          console.log('Received Selected State:' + state);
          this.updateSourceButton(i, 'state', state);
        }
      );
    }
  }

  ngOnDestroy(): void {
    for (let i = 0; i < this.sources; i++) {
      CrComLib.unsubscribeState(
        's',
        `MainPage.SourceList.Button${i + 1}Text`,
        this.titleSubscription[i]
      );

      CrComLib.unsubscribeState(
        'b',
        `MainPage.SourceList.Button${i + 1}Selected`,
        this.selectedSubscription[i]
      );
    }
  }

  selectSource(index: number): void {
    CrComLib.pulseDigital(`MainPage.SourceList.Button${index + 1}ItemPress`);
  }

  updateSourceButton(index: number, key: keyof SourceButton, value: any) {
    this.ngZone.run(() =>
      this.SourceButton.update((arr) =>
        arr.map((v, i) => (i === index ? { ...v, [key]: value } : v))
      )
    );
  }
}

<ul class="source-list">
  @for (button of SourceButton(); track $index) {
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource($index)"
      [class.selected]="button.state"
    >
      {{ button.title }}
    </button>
  </li>
  } @empty { }
</ul>

<!-- if we were doing this long hand without using the framework's @for loop

<ul class="source-list">
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(0)"
      [class.selected]="SourceButton()[0].state"
    >
      {{ SourceButton()[0].title }}
    </button>
  </li>
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(1)"
      [class.selected]="SourceButton()[1].state"
    >
      {{ SourceButton()[1].title }}
    </button>
  </li>
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(2)"
      [class.selected]="SourceButton()[2].state"
    >
      {{ SourceButton()[2].title }}
    </button>
  </li>
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(3)"
      [class.selected]="SourceButton()[3].state"
    >
      {{ SourceButton()[3].title }}
    </button>
  </li>
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(4)"
      [class.selected]="SourceButton()[4].state"
    >
      {{ SourceButton()[4].title }}
    </button>
  </li>
  <li class="source-list__item">
    <button
      class="source-list__button"
      (click)="selectSource(5)"
      [class.selected]="SourceButton()[5].state"
    >
      {{ SourceButton()[5].title }}
    </button>
  </li>
</ul>
-->

// mux-521-react-complete/src/components/SourceList/SourceList.tsx
import React, { useState, useEffect, useContext } from 'react';

// Import the styles from the scss file
import styles from './SourceList.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

// Define the SourceButton interface
interface SourceButton {
  title: string;
  state: boolean;
}

// Define the SourceListComponentProps interface
interface SourceListComponentProps {
  sources: number;
}

const SourceListComponent: React.FC<SourceListComponentProps> = ({ sources }) => {

  // Access the subscribeState, unsubscribeState, and pulseDigital functions
  const { subscribeState, unsubscribeState, pulseDigital } = useContext(CrComLibContext);

  // Initialize the sourceButtons state with the correct type
  const [sourceButtons, setSourceButtons] = useState<SourceButton[]>([]);

  useEffect(() => {
    // Initialize sourceButtons with the default values
    const newSourceButtons = Array.from({ length: sources }, () => ({ title: '', state: false }));

    // Update the sourceButtons state
    setSourceButtons(newSourceButtons);

    // Subscribe to each source button
    const subscriptions = newSourceButtons.map((_, index) => ({
      
      // Subscribe to the title state
      titleSubscription: subscribeState(
        's',
        `MainPage.SourceList.Button${index + 1}Text`,
        (title: string) => updateSourceButton(index, 'title', title)
      ),

      // Subscribe to the state of each source button
      stateSubscription: subscribeState(
        'b',
        `MainPage.SourceList.Button${index + 1}ItemSelected`,
        (state: boolean) => updateSourceButton(index, 'state', state)
      ),
    }));

    // Cleanup function for component unmount
    return () => {
      // Unsubscribe from each source button
      subscriptions.forEach(({ titleSubscription, stateSubscription }, index) => {
        unsubscribeState('s', `MainPage.SourceList.Button${index + 1}Text`, titleSubscription);
        unsubscribeState('b', `MainPage.SourceList.Button${index + 1}ItemSelected`, stateSubscription);
      });
    };
  }, [sources, subscribeState, unsubscribeState]); // The useEffect hook will only run when the sources, subscribeState, or unsubscribeState functions change

  // Update the sourceButtons state based on the index and key
  const updateSourceButton = (index: number, key: 'title' | 'state', value: string | boolean) => {
    setSourceButtons(prevButtons => prevButtons.map((button, i) =>
      i === index ? { ...button, [key]: value } : button
    ));
  };

  // Function to select a source button
  const selectSource = (index: number) => {
    pulseDigital(`MainPage.SourceList.Button${index + 1}ItemPress`);
  }

  // Render the component UI
  return (
    <ul className={styles["source-list"]}>
      {sourceButtons.length ? (
        sourceButtons.map((button, index) => (
          <li key={index} className="source-list__item">
            <button
              className={`${styles['source-list__button']} ${button.state ? styles['selected'] : ''}`}
              onClick={() => selectSource(index)}
            >
              {button.title}
            </button>
          </li>
        ))
      ) : (
        // Handling the case where there are no source buttons
        <li className="source-list__item">No sources available</li>
      )}
    </ul>
  );
};

export default SourceListComponent;
