// mux-521-angular-complete/src/app/main-page/main-page.component.ts
import { Component, OnDestroy, OnInit, signal, NgZone } from '@angular/core';

// The AirMediaComponent is used to display the AirMedia popup.
import { AirmediaComponent } from '../popups/airmedia/airmedia.component';
// The AppleTvComponent is used to display the Apple TV popup.
import { AppleTvComponent } from '../popups/apple-tv/apple-tv.component';
// The NvxInfoComponent is used to display the NvxInfo popup.
import { NvxInfoComponent } from '../popups/nvx-info/nvx-info.component';
// The PowerConfirmComponent is used to display the PowerConfirm popup.
import { PowerConfirmComponent } from '../popups/power-confirm/power-confirm.component';
// The SourceListComponent is used to display the SourceList widget.
import { SourceListComponent } from '../components/source-list/source-list.component';
// The TitleBarComponent is used to display the TitleBar widget.
import { TitleBarComponent } from '../components/title-bar/title-bar.component';
// The VolumeComponent is used to display the Volume widget.
import { VolumeComponent } from '../components/volume/volume.component';

declare var CrComLib: CrComLib;

enum Source {
  None = -1,
  AppleTV,
  AirMedia,
  GlobalSource2,
  GlobalSource3,
  GlobalSource4,
  GlobalSource5,
}

@Component({
  standalone: true,
  selector: 'app-main-page',
  templateUrl: './main-page.component.html',
  styleUrl: './main-page.component.scss',
  imports: [
    AirmediaComponent,
    AppleTvComponent,
    NvxInfoComponent,
    PowerConfirmComponent,
    SourceListComponent,
    TitleBarComponent,
    VolumeComponent,
  ],
})
export class MainPageComponent implements OnInit, OnDestroy {
  // Declare the Source enum.
  Source = Source;

  // The number of sources we are displaying.
  readonly Sources = 6 ;

  source = signal(Source.None);

  // Declare the sourceSubscription array.
  sourceSubscription: string[] = new Array(6);

  constructor(private ngZone: NgZone) {}

  ngOnInit(): void {
    for (let i = 0; i < this.Sources; i++) {
      this.sourceSubscription[i] = CrComLib.subscribeState(
        'b',
        // Our list is 1 based, so we add 1 to the index.
        `MainPage.SourceList.Button${i + 1}ItemSelected`,
        (state: boolean) => {
          // If the state is false, return as we are going to convert positive states to the Source enum.
          if(!state) return;
          this.ngZone.run(() => this.source.set(i));
          console.log('Info -> main-page -> The source is now: ' + Source[this.source()]);
        }
      );
    }
  }

  ngOnDestroy(): void {
    for (let i = 0; i < this.Sources; i++) {
      CrComLib.unsubscribeState(
        'b',
        // Our list is 1 based, so we add 1 to the index.
        `MainPage.SourceList.Button${i + 1}Selected`,
        this.sourceSubscription[i]
      );
    }
  }
}

<div class="page">
  <app-power-confirm />
  <app-title-bar />
  <div class="content">
    <app-source-list [sources]="Sources" />

    <div class="control-container">
      <span
        class="source-title"
        data-ch5-textcontent="MainPage.SourceFeedbackLabel.Indirect"
      ></span>

      <div class="source-content">
        @switch(source())
        {
          @case(Source.None){}
          @case(Source.AirMedia){<app-airmedia /> }
        @case(Source.AppleTV){ <app-apple-tv /> }
        @default { <app-nvx-info /> }
      }
      </div>
    </div>
    <app-volume />
  </div>
</div>

// mux-521-react-complete/src/components/MainPage/MainPage.tsx
import React, { useState, useEffect, useContext } from 'react';

// Import the styles from the scss file
import styles from './MainPage.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

// Import the components used in this component
import PowerConfirmComponent from '../PowerConfirm/PowerConfirm';
import TitleBarComponent from '../TitleBar/TitleBar';
import SourceListComponent from '../SourceList/SourceList';
import VolumeComponent from '../Volume/Volume';
import NvxInfoComponent from '../NvxInfo/NvxInfo';
import MediaControlComponent from '../AppleTV/AppleTV';
import AirMediaComponent from '../AirMedia/AirMedia';

// Define the source enum
enum eSource {
  None = -1,
  AppleTV,
  AirMedia,
  GlobalSource2,
  GlobalSource3,
  GlobalSource4,
  GlobalSource5,
}

// Define the number of sources
const sourcesCount = 6;

const MainPage: React.FC = () => {
  
  // Access the subscribeState and unsubscribeStatefunctions
  const { subscribeState, unsubscribeState } = useContext(CrComLibContext);

  // Initialize the source state
  const [source, setSource] = useState<eSource>(eSource.None);

  useEffect(() => {
    // Subscribe to each source button
    const subscriptionIds = Array.from({ length: sourcesCount }, (_, index) => {
      return subscribeState('b', `MainPage.SourceList.Button${index + 1}ItemSelected`, (state: boolean) => {
        if (!state) return;
        setSource(index as eSource);
        console.log('Info -> main-page -> The source is now: ' + eSource[index]);
      });
    });

    // Cleanup function for component unmount
    return () => {
      subscriptionIds.forEach((id, index) => unsubscribeState('b', `MainPage.SourceList.Button${index + 1}ItemSelected`, id));
    };
  }, [subscribeState, unsubscribeState]);

  // Render the correct source content
  const sourceContent = () => {
    switch (source) {
      case eSource.None: return null;
      case eSource.AirMedia: return <AirMediaComponent />;
      case eSource.AppleTV: return <MediaControlComponent />;
      default: return <NvxInfoComponent />;
    }
  };

  // Render the component UI
  return (
    <div className={`page ${styles.page}`}>
      <PowerConfirmComponent />
      <TitleBarComponent />
      <div className="content">
        <SourceListComponent sources={sourcesCount} />
        <div className={styles['control-container']}>
          <span className={styles['source-title']}></span>
          <div className={styles['source-content']}>
            {sourceContent()}
          </div>
        </div>
        <VolumeComponent />
      </div>
    </div>
  );
}

export default MainPage;
