// mux-521-angular-complete/src/app/popups/power-confirm/power-confirm.component.ts
import { Component, NgZone, signal } from '@angular/core';
import { FadeInOutAnimation } from '../../animations/animations';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-power-confirm',
  templateUrl: './power-confirm.component.html',
  styleUrl: './power-confirm.component.scss',
  animations: [FadeInOutAnimation],
})
export class PowerConfirmComponent {
  // Visibility state of the component
  visible = signal(false);
  // Subscription to the visibility state
  visibilitySubscrption!: string;
  // Handle for the timeout
  timerHandle: any;

  constructor(private ngZone: NgZone) {}
  // ngOnInit lifecycle hook
  ngOnInit(): void {
    // Subscribe to the visibility state
    this.visibilitySubscrption = CrComLib.subscribeState(
      'b',
      'MainPage.PowerOffOk.Visibility',
      (state: boolean) => {
        console.log('Power On / Off Visibility: ' + state);
        // Run inside Angular's zone to trigger change detection
        this.ngZone.run(() => this.visible.set(state));
        // Toggle the timeout based on the state
        this.ToggleTimeout(state);
      }
    );
  }

  // ngOnDestroy lifecycle hook
  ngOnDestroy(): void {
    // Unsubscribe from the visibility state
    CrComLib.unsubscribeState(
      'b',
      'MainPage.PowerOffOk.Visibility',
      this.visibilitySubscrption
    );
    // Clear the timeout
    clearTimeout(this.timerHandle);
  }

  // Method to toggle the timeout
  ToggleTimeout(state: boolean) {
    if (state) {
      // If the state is true, set a timeout to call the No method after 10 seconds
      this.timerHandle = setTimeout(() => {
        this.No();
      }, 10000);
    } else {
      // If the state is false, clear the timeout
      clearTimeout(this.timerHandle);
    }
  }

  // Method to handle the Yes action
  Yes(): void {
    // Pulse the Yes digital join.
    CrComLib.pulseDigital('PowerOffOk.PowerOffYesButton.Press');
  }

  // Method to handle the No action
  No(): void {
    // Pulse the No digital join.
    CrComLib.pulseDigital('PowerOffOk.PowerOffNoButton.Press');
  }
}

@if(visible()) {
<div class="power-confirm" @fadeIn @fadeOut>
  <span class="power-confirm__title">Power System Off?</span>
  <div class="power-confirm__buttons">
    <button
      class="power-confirm__button power-confirm__button--green"
      (click)="Yes()"
    >
      Yes
    </button>
    <button
      class="power-confirm__button power-confirm__button--red"
      (click)="No()"
    >
      No
    </button>
  </div>
</div>
}

// mux-521-react-complete/src/components/PowerConfirm/PowerConfirm.tsx
import React, { useState, useEffect, useContext, useRef, useCallback } from 'react';

// Import the styles from the scss file
import styles from './PowerConfirm.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const PowerConfirmComponent = () => {

  // Access the subscribeState, unsubscribeState, and pulseDigital functions
  const { subscribeState, unsubscribeState, pulseDigital } = useContext(CrComLibContext);

  // Initialize the visible state
  const [visible, setVisible] = useState(false);

  // Handle for the visibility subscription
  const visibilitySubscription = useRef("");

  // Handle for the timeout
  const timerHandle = useRef<number | null>(null);

  // Define the handleYes and handleNo methods, wrapped in a useCallback hook to prevent unnecessary re-renders
  const handleYes = useCallback(() => {
    pulseDigital('PowerOffOk.PowerOffYesButton.Press');
  }, [pulseDigital]);

  const handleNo = useCallback(() => {
    pulseDigital('PowerOffOk.PowerOffNoButton.Press');
  }, [pulseDigital]);

  useEffect(() => {

    // Toggle the popup visibility and handle the timeout
    const toggleTimeout = (state: boolean) => {
      if (state) {
        // If the state is true, set a timeout to call the noMethod after 10 seconds
        timerHandle.current = window.setTimeout(handleNo, 10000);
      } else {
        // If the state is false, clear the timeout
        if (timerHandle.current !== null) window.clearTimeout(timerHandle.current);
      }
    };

    // Subscribe to the Power Off visibility
    visibilitySubscription.current = subscribeState(
      'b',
      'MainPage.PowerOffOk.Visibility',
      (state: boolean) => {
        console.log('Power On / Off Visibility: ' + state);
        setVisible(state);
        toggleTimeout(state);
      }
    );

    // Cleanup function for component unmount
    return () => {
      // Clear the timeout
      if (timerHandle.current !== null) window.clearTimeout(timerHandle.current);
      unsubscribeState(
        'b',
        'MainPage.PowerOffOk.Visibility',
        visibilitySubscription.current
      );
    };
  }, [subscribeState, unsubscribeState, handleNo]);

  // Render the component UI
  return (
    <div>
      {visible && (
        <div className={styles["power-confirm"]}>
          <span className={styles["power-confirm__title"]}>Power System Off?</span>
          <div className={styles["power-confirm__buttons"]}>
            <button className={`${styles['power-confirm__button']} ${styles['power-confirm__button--green']}`} onClick={handleYes}>Yes</button>
            <button className={`${styles['power-confirm__button']} ${styles['power-confirm__button--red']}`} onClick={handleNo}>No</button>
          </div>
        </div>
      )}
    </div>
  );
};

export default PowerConfirmComponent;
