// mux-521-angular-complete/src/app/popups/nvx-info/nvx-info.component.ts
import { Component, OnDestroy, OnInit, NgZone,signal } from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-nvx-info',
  templateUrl: './nvx-info.component.html',
  styleUrl: './nvx-info.component.scss',
})
export class NvxInfoComponent implements OnInit, OnDestroy {
  // IP Address of the NVX device
  address = signal('0.0.0.0');
  // Subscription to the address serial join
  addressSubscription!: string;

  constructor(private ngZone: NgZone) {}

  // ngOnInit lifecycle hook
  ngOnInit(): void {
    // Subscribe to the ip address join
    this.addressSubscription = CrComLib.subscribeState(
      's',
      'NvxInfo.NvxAddressFb.Indirect',
      (address: string) => {
        console.log('NVX Address Received: ' + address);
        // Run inside Angular's zone to trigger change detection
        this.ngZone.run(() => this.address.set(address));
      }
    );
  }

  // ngOnDestroy lifecycle hook
  ngOnDestroy(): void {
    // Unsubscribe from the ip address join
    CrComLib.unsubscribeState(
      's',
      'NvxInfo.NvxAddressFb.Indirect',
      this.addressSubscription
    );
  }
}

<div class="nvx-info">
  <span>NVX Address:</span>
  <span class="text-highlight">{{ address() }}</span>
</div>

// mux-521-react-complete/src/components/NvxInfo/NvxInfo.tsx
import React, { useState, useEffect, useContext } from 'react';

// Import the styles from the scss file
import styles from './NvxInfo.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

const NvxInfoComponent: React.FC = () => {

  // Access the subscribeState and unsubscribeState functions
  const { subscribeState, unsubscribeState } = useContext(CrComLibContext);

  // Initialize the address state
  const [address, setAddress] = useState<string>('0.0.0.0');

  useEffect(() => {
    // Subscribe to the NVX address
    const addressSubscription = subscribeState(
      's',
      'NvxInfo.NvxAddressFb.Indirect',
      (address: string) => {
        console.log('Nvx Info Address: ' + address);
        setAddress(address);
      }
    );

    // Cleanup function for component unmount
    return () => {
      unsubscribeState(
        's',
        'NvxInfo.NvxAddressFb.Indirect',
        addressSubscription
      );
    };
  }, [subscribeState, unsubscribeState]);

  // Render the component UI
  return (
    <>
      <div className={styles["nvx-info"]}>
        <span>NVX Address:</span>
        <span className="text-highlight">{address}</span>
      </div>
    </>
  );
};

export default NvxInfoComponent;
