// mux-521-angular-complete/src/app/components/examples/d-pad/d-pad.component.ts
import { Component, Input } from '@angular/core';

declare var CrComLib: CrComLib;

@Component({
  standalone: true,
  selector: 'app-d-pad-example',
  templateUrl: './d-pad.component.html',
  styleUrl: './d-pad.component.scss',
})

export class DPadExampleComponent {
  // Use the @Input decorator to define the join property.
  @Input() join: string = 'MediaControl.Dpad';

  /** Pulses the up digital join */
  up(): void {
    CrComLib.pulseDigital(this.join + '.Up');
  }
  /** Pulses the down digital join */
  down(): void {
    CrComLib.pulseDigital(this.join + '.Down');
  }
  /** Pulses the up digital join */
  left(): void {
    CrComLib.pulseDigital(this.join + '.Left');
  }
  /** Pulses the up digital join */
  right(): void {
    CrComLib.pulseDigital(this.join + '.Right');
  }
  /** Pulses the up center join */
  center(): void {
    CrComLib.pulseDigital(this.join + '.Center');
  }
}

<nav class="d-pad">
  <div class="d-pad__corner--top-left"></div>
  <button class="d-pad__button" (click)="up()">
    <img src="assets/images/icons/navigation/up.svg" />
  </button>
  <div class="d-pad__corner--top-right"></div>
  <button class="d-pad__button" (click)="left()">
    <img src="assets/images/icons/navigation/left.svg" />
  </button>
  <button class="d-pad__button d-pad__button--centre" (click)="center()"></button>
  <button class="d-pad__button" (click)="right()">
    <img src="assets/images/icons/navigation/right.svg" />
  </button>
  <div class="d-pad__corner--bottom-left"></div>
  <button class="d-pad__button" (click)="down()">
    <img src="assets/images/icons/navigation/down.svg" />
  </button>
  <div class="d-pad__corner--bottom-right"></div>
</nav>

// mux-521-react-complete/src/components/DPad/DPad.tsx
import React, { useContext } from 'react';

// Import the styles from the scss file
import styles from './DPad.module.scss';

// Import the CrComLibContext
import { CrComLibContext } from '../../contexts/CrComLibContext';

// Create a type for the props
type DNavComponentProps = {
  join: string;
}

const DNavComponent: React.FC<DNavComponentProps> = ({ join = 'MediaControl.Dpad'}) => {
  // Access the pulseDigital function
  const { pulseDigital } = useContext(CrComLibContext);

  // Create the functions to send the digital pulses
  const up = () => {
    pulseDigital(`${join}.Up`);
  };

  const down = () => {
    pulseDigital(`${join}.Down`);
  };

  const left = () => {
    pulseDigital(`${join}.Left`);
  };

  const right = () => {
    pulseDigital(`${join}.Right`);
  };

  const ok = () => {
    pulseDigital(`${join}.Center`);
  };

  // Render the component UI
  return (
    <nav className={styles["d-pad"]}>
      <div className={styles["d-pad__corner--top-left"]}></div>

      <button className={styles["d-pad__button"]} onClick={up}>
        <img src="./images/icons/navigation/up.svg" alt="Up" />
      </button>

      <div className={styles["d-pad__corner--top-right"]}></div>

      <button className={styles["d-pad__button"]} onClick={left}>
        <img src="./images/icons/navigation/left.svg" alt="Left" />
      </button>

      <button className={`${styles['d-pad__button']} ${styles['d-pad__button--centre']}`} onClick={ok}>

      </button>
      <button className={styles["d-pad__button"]} onClick={right}>
        <img src="./images/icons/navigation/right.svg" alt="Right" />
      </button>

      <div className={styles["d-pad__corner--bottom-left"]}></div>

      <button className={styles["d-pad__button"]} onClick={down}>
        <img src="./images/icons/navigation/down.svg" alt="Down" />
      </button>

      <div className={styles["d-pad__corner--bottom-right"]}></div>
    </nav>
  );
};

export default DNavComponent;
